networks:
  dev:

services:
  backend:
    container_name: afgo_container
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    networks:
    - dev
    depends_on: 
      - clickhouse-server
    ports:
    - "1111:1111"
    volumes:
      - .:/afgo_container

  clickhouse-server:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    networks:
    - dev
    ports:
    - "8123:8123"
    - "9000:9000"
    environment:
      - CLICKHOUSE_USER=base_user
      - CLICKHOUSE_PASSWORD=base_user_pass
      - CLICKHOUSE_DB=base_db
